### ISSUE TITLE
Try and ensure everyone is committing to the project

### ISSUE THREAD

**Issue by Jen-Harris** [fac-12/ssbt#40]
At the moment the commit history is quite varied by person (This may be because of pairing on a particular laptop) but do try and keep this equal! 

![image](https://user-images.githubusercontent.com/26116988/32096704-208108bc-baff-11e7-8a53-4b0e9e0acb63.png)

**Comment by rebecacalvoquintero** [comment]
Try to use pomodoro!! 20 mins on each computer :) And always work in pairs....everybody will benefit from it! :)

**Comment by rb50** [comment]
Thanks for the feedback- we realised that although everyone was committing, github wasn't picking up mine and Sophie's commits - we've now fixed this through some terminal configuration we needed to do so all sorted now 😄
