### ISSUE TITLE
Just a little suggestion

### ISSUE THREAD

**Issue by rebecacalvoquintero** [fac-12/ssbt#48]
As user experience, I would not include 'SSBT' in the navbar unless it is a favicon or the logo, in this case it gives the impression it is also a link that will direct you to another place in the app.

This is completely personal...so obvs you can ignore this completely :)

![screen shot 2017-10-27 at 10 36 28](https://user-images.githubusercontent.com/23295662/32097830-b4100436-bb02-11e7-8fec-c4ff43e0bcc7.png)

**Comment by rb50** [comment]
Thanks for the feedback - we've decided to keep the logo as it does link back to the top of the page if the user is elsewhere in the page.

**Comment by rebecacalvoquintero** [comment]
I did missed that!! now it makes sense!! @rb50
