### ISSUE TITLE
Adding a favicon?

### ISSUE THREAD

**Issue by jamiecoe** [fac-12/ssbt#51]
Another small thing, have you thought about adding a favicon image? Eg:

<img width="58" alt="screen shot 2017-10-27 at 10 41 21" src="https://user-images.githubusercontent.com/18463718/32098066-61ac8f7e-bb03-11e7-89d9-eade31f3413e.png">

You can add it inside <head> of your index.html with this line:
`<link rel="shortcut icon" href="yourfavicon.ico">`
A favicon is a tiny square image, usually about 64x64. There's an online generator here: 
https://www.favicon-generator.org/

**Comment by tundeaji1232** [comment]
favicon added
