### ISSUE TITLE
HTML outliner result

### ISSUE THREAD

**Issue by Johanna-hub** [fac-12/ssbt#53]
Great result from the HTML outliner tool!  Just need to title pictures, and body

![screen shot 2017-10-27 at 10 50 31](https://user-images.githubusercontent.com/24194579/32098486-c57ea720-bb04-11e7-8f7a-e7b478ce9c4c.png)

**Comment by sophielevens** [comment]
completed but will raise another issue to see if icons can be ignored by HTML5 outliner
