### ISSUE TITLE
review contributions 

### ISSUE THREAD

**Issue by jessicasalmon** [fac-12/ssbt#60]
Hey @shannonjensen @tundeaji1232 @rb50 @sophielevens 

Really great work this week :tada:

I wanted to flag up your contribution graph, it's quite uneven (and I hate to flag it up but you're completely missing a team member off of your contributions). Totally understandable in your first week of pairing, but I strongly suggest that you discuss what led to this at your team stop go continue as it's really important that everyone is contributing equally and that you're swapping machines often enough during pairing. 

<img width="1056" alt="screen shot 2017-10-27 at 11 35 25" src="https://user-images.githubusercontent.com/19147734/32100164-f963d42e-bb0a-11e7-9d0d-9a01b6ea63aa.png">

I'll be around in the afternoon, so if you've any questions around pairing (or anything) - let me know :)

**Comment by shannonjensen** [comment]
Just want to let you know that this is because two of our members' commits were not showing up due to an issue with linked email addresses that we are solving!

**Comment by jessicasalmon** [comment]
Hey @shannonjensen - that's great to hear :) Hope you find a fix soon and let me know if I can help with anything.
